language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "lpymvB/8q92fy5b52dCYUYvBuSLWORjqEGuHWKmEHXu6KbV1oMN0bp1BMryETafujZHscvaYgtho8gG5x+7EpucVU/ib1NWHeN3lrbDGrgwqTOVPnkEuBlzT2lUKw7ZwY4VtlScxmI8KRGj/larf1Ii5Tei4aNM7X4sWXO73AuZJBQLVgWP1E8DBtoHUcpaPPQPelr0q7HYUfaLakGpqzK4UXCtI8QASXV47C+3OUBJVLvl+PzNsMsAwHYPKj9as/OUwA5TgMiNXaWDyi4WolznJRHGK6ctM6XaVX7QPXbk3GfX1DpIJJIBioFKv4m3vQLmTRq76h4brZhe/OkY2q0a5q6MeNXS6VN7qopM+N160KTao98BseKaANwOyYxD9gPVFi2XXGvYlo0wbFh/Xj4by2UBuBIoyHJ9yR2wsAmohyCicHXOvPd0wZoJYx0y8Q3lg01vw+ZbOCAQtzURXIOxjUtQDlKYE6tuBnz4cEyAp0xFIVgDf1rHJ5fovMzu60345GU8/yBztaZnVlefp7Re4hBYggbdRy2s5VxmT66NVxSeHF4eOBsI73yq5fbUMmYDa13n/lZhJOzE/A49GEFnLhMAMbBpZtOHD7Opg/CdA64QrjO0CYcrpoflwhgc5UOGhuMiH0hO0BN+zXk01KmOHGe9XbX9EXjjUyBDrlUo="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
